#!/bin/bash

LOGFILE=/usr/local/careview/logs/init/stores.init.log
touch $LOGFILE
echo "`date`: Starting stores" >>$LOGFILE

function ctrl_stores () {
    local arg=$1

    for i in archive history purge buffer; do
        local store=${i}_store
        case $arg in
            start)
                echo "Starting $store..." >>$LOGFILE
                svc -u /etc/service/$store >>$LOGFILE 2>&1
            ;;
            stop)
                echo "Stopping $store..." >>$LOGFILE
                svc -d /etc/service/$store >>$LOGFILE 2>&1
            ;;
            restart)
                echo "Restarting $store..." >>$LOGFILE
                svc -d /etc/service/$store >>$LOGFILE 2>&1
                sleep 1
                svc -u /etc/service/$store >>$LOGFILE 2>&1
            ;;
            *)
                echo "Unknown action '$arg'!"; >>$LOGFILE
                exit 0;
            ;;
        esac
    done;

    return;
}

trap "ctrl_stores stop ; exit 0" SIGTERM;

ctrl_stores start;

while true; do
    sleep 10;
done;

