#!/bin/bash

function import_videos () {
    local store=$1
    local FILELIST=( );
    local FILECOUNT=0;
    while read _fn; do
        FILELIST[$FILECOUNT]="$_fn";
        FILECOUNT=$(($FILECOUNT+1));
        if [ $FILECOUNT -ge 50 ]; then
            /usr/local/careview/sbin/import_videos.php $store "${FILELIST[@]}"
            FILELIST=( );
            FILECOUNT=0;
        fi;
    done;

    [ $FILECOUNT -gt 0 ] && /usr/local/careview/sbin/import_videos.php $store "${FILELIST[@]}"

    return 0;
}


echo "Starting Buffer Store"
date >> /usr/local/careview/logs/stores/init/buffer.log 2>&1

# always call import on buffer device's videos... 
# as it has little space to play with, if a video
# is not in the database, it'll run out of space
# rather quickly

# addendum: export NO_WAIT_ON_FAI so this call NEVER waits... 
# the buffer store never has many videos on it, so this will not
# take too long, but we don't want the buffer store's startup to
# be delayed for the risk of the buffer device filling up before
# the store can move them to another store
#   -- Stephen, 2011-05-04
export NO_WAIT_ON_FAI=1

cd /usr/local/careview/video/buffer;
find ./ -type f -name '*-*.*' | import_videos buffer;

exec /usr/local/careview/bin/store_manager.php --force --logfile stores/buffer.log --quiet --manage buffer >> /usr/local/careview/logs/stores/init/buffer.log 2>&1

