#!/bin/bash

exec >>/usr/local/careview/logs/init/watchdog.init.log 2>&1
if [ -e /usr/local/careview/flags/doing_cold_restart.flag ] ; then
    echo "`date`: Watchdog pulse skipped because cold restart flag is raised"
    logger 'Watchdog pulse skipped because cold restart flag is raised'
elif [ -e /usr/local/careview/flags/force_cold_restart.flag ] ; then
    echo "`date`: Watchdog pulse skipped because force cold restart flag is raised"
    logger 'Watchdog pulse skipped because force cold restart flag is raised'
else
    echo "`date`: Watchdog pulse"
    # The watchdog pulse script generates an appropriate logger event
    /usr/local/sbin/watchdog_pulse.sh
fi
sleep 58
