#!/bin/bash

logfile=/usr/local/careview/logs/init/mysql_monitor.log

function logger () {
    echo "`date`: $@" >> $logfile
}

logger "Starting mysql service monitor"

while true; do
    if ! /etc/init.d/mysql start | grep 'already running'; then
        logger "Mysql was not running!  Restarted..."
    fi
    sleep 60;
done;

