#!/bin/bash
LOGFILE=/usr/local/careview/logs/stores/init/archive.log
IMPORT_LOGFILE=/usr/local/careview/logs/stores/init/import.log

function logit () {
    echo "$*" >> $LOGFILE
}

function map_out () {
    local _log=$1
    exec 3<&1
    exec 4<&2
    exec >>$_log 2>&1
    return;
}

function restore_out () {
    exec 1<&3
    exec 2<&4
    return;
}


function import_old_videos () {
    local storename=$1
    logit "  -- importing videos...";
    /usr/bin/find ./ -type f -name "*-*.mpg" | /usr/local/careview/sbin/import_videos.php $storename -
    SUCCESS=$(($SUCCESS || $?))
    logit "  ...done"

    logit "  -- importing events..."
    /usr/bin/find ./ -type f -name "*-*.mpg.info" | /usr/local/careview/sbin/import_events.php -
    SUCCESS=$(($SUCCESS || $?))
    logit "  ...done"

    return $SUCCESS;
}


function import_new_videos () {
    local store=$1
    local FILELIST=( );
    local FILECOUNT=0;
    while read _fn; do
        FILELIST[$FILECOUNT]="$_fn";
        FILECOUNT=$(($FILECOUNT+1));
        if [ $FILECOUNT -ge 50 ]; then
            /usr/local/careview/sbin/import_videos.php $store "${FILELIST[@]}"
            FILELIST=( );
            FILECOUNT=0;
        fi;
    done;

    [ $FILECOUNT -gt 0 ] && /usr/local/careview/sbin/import_videos.php $store "${FILELIST[@]}"

    return 0;
}

function import_video_files () {
    [ -e /usr/local/careview/etc/import_videos.flag ] || return 0;
    echo "`date`: Importing old videos into storage engine..." 
    
    ln -s /var/video/archive /usr/local/careview/video/temp_old_dir;

    for vidpath in buffer archive temp_old_dir; do 
        [ -d /usr/local/careview/video/$vidpath ] || continue;

        echo "  Importing from $vidpath drive..."
        if ! cd /usr/local/careview/video/$vidpath; then
            echo "    ERROR: Unable to chdir to /usr/local/careview/video/$vidpath"
            continue;
        fi

        if [ "$vidpath" = "buffer" ]; then
            import_old_videos $vidpath >> $LOGFILE 2>&1;

        else
            vidpath='history'
            # Importing from old archive layout...
            for archive_dir in `find 20[0-9][0-9] -type d | sort -r`; do
                [ -d $archive_dir ] || continue;
                pushd $archive_dir || continue;
                import_old_videos $vidpath >> $LOGFILE 2>&1;
                popd
                rmdir -p $archive_dir;
            done;

            # Importing from new archive layout, into database (after reimage...)
            # 
            # 2011-08-26:  This is being removed from this script, as this is
            # now being done much faster in the validate_videos.php script.
            #    --Stephen
#            for store_dir in 3M 6M 9M Perm history purge; do
#                [ -d $store_dir ] || continue;
#                store_name=$store_dir
#                grep '^[369P]' <<<"$store_dir" && store_name="archive$store_dir";
#                find $store_dir/ -type f -name '*.mpg' -o -name '*.flv' | import_new_videos $store_name;
#            done;
        fi
            
        echo "  Finished importing from $vidpath."
    done;

    cd /usr/local/careview;
    rm /usr/local/careview/video/temp_old_dir;

    # remove year/month/day directories
    /usr/bin/find ./[0-9][0-9]* -type d -name "[0-9][0-9]*" -delete

    echo "...Finished importing videos and events from into new storage engine."
    if [ $SUCCESS -eq 0 ]; then rm /usr/local/careview/etc/import_videos.flag; fi

    return 0;
}

map_out $LOGFILE

echo "`date`: Starting Archive Store"

SUCCESS=0

restore_out;

map_out $IMPORT_LOGFILE
import_video_files
restore_out;

map_out $LOGFILE

echo "Recalculating store usages..." 
/usr/local/careview/sbin/calculate_store_usages.sh 

echo "Validating videos..." 
/usr/bin/php /usr/local/careview/sbin/validate_videos.php 

# these stores wont be needed for much longer... but for now they are 
# here to slowly move videos from their storage to the history store
# see bug #871  --Stephen

echo "Starting stores..." 
exec /usr/local/careview/bin/store_manager.php --force --logfile stores/archive.log --quiet --manage archive archive3M archive6M archive9M archivePerm 

