#!/bin/bash

LOG=/usr/local/careview/logs/init/memcached.init.log
exec >>$LOG 2>&1

# This is a workaround for when memcached is left running and parented to init.
# This happens when the memcached package is first installed or when it is updated
# after a reboot; i.e. the memcached package's postinst starts memcached before
# the supervise service starts. As explained in bug #764, sometimes when this
# happens we don't get video, so we have to fix it.
downed_services=
for pid in `pidof memcached 2>/dev/null` ; do
    if [ `ps -fp $pid | awk '$2 ~ "'$pid'" && $3 ~ "1" {print $2}'` ] ; then
        echo "`date`: Killing orphaned memcached process $pid"
        # Must take down all services using memcached or they will
        # go insane causing stream_test to reboot the box
        for svc in copier stream_test yuv_to_jpeg ; do
            svc=/etc/service/$svc
            if svstat $svc | grep -q "$svc: *up " ; then
                echo "Taking down $svc"
                downed_services="$downed_services $svc"
                svc -d $svc
            fi
        done
        kill $pid
    fi
done

if [ ".$downed_services" != "." ] ; then
    # We need to restart the services we stopped, but they must start after memcached
    # is running. So wait a few seconds for memcached to come up, but if for some reason
    # it never comes up, terminate so we don't have a endless number of bash scripts running.
    bash >>$LOG 2>&1 <<EOF &
for i in 1 2 3 4 5 ; do
    if pidof memcached >/dev/null 2>&1 ; then
        echo 'Restarting $downed_services'
        svc -u $downed_services
        exit 0
    else
        sleep 1
    fi
done
echo 'memcached never came up! $downed_services are being left down!'
exit 1
EOF
fi

echo "`date`: Starting memcached"
exec /usr/bin/memcached -m 16 -u nobody
