.PHONY +=   build all link unlink clean debug install subdirs clean_subdirs $(PROD) $(TESTS)
# this file is to be included by the version specific Makefile under cellnet-VER.
# it contains all the default options and targets.  The including Makefile should
# only need to specify the version: $(CV_BUILD_VERSION), the source files: $(SRCS), the
# production apps: $(PROD), and the testing apps: $(TESTS).
#
# --Stephen Ecker.  2011-04-08

DEBUG_FLAGS = -D_DEBUG_FLOW_

MKDIR   =   /bin/mkdir
CC	    =   /usr/bin/gcc
CFLAGS  +=   -O2 -Wall -Wno-format-extra-args -I../include -I./headers -std=gnu99 -mmmx -msse -msse2 -msse3 $(DEBUG_FLAGS) -D_SHOW_WARNINGS_ -D_SHOW_ERRORS_ -D_USE_POSIX_SHM_
DEPEND	=	-lm -lgd -lrt

HEADDIR	=	headers
BASEDIR =   /usr/local/ezfw
BUILD   =   ../../build
OBJDIR	=	.objs
SHLIBDIR=	../../../modules

# convert all src filenames to object filenames under the objdir
OBJS	 = $(addprefix $(OBJDIR)/, $(SRCS:.c=.o))
SHLIBS	=	$(addprefix $(SHLIBDIR)/, $(SHSRCS:.c=.so))


APPS	 =  $(PROD) $(TESTS)

# make all apps
all	     : subdirs $(APPS) $(SHLIBS)
# link compiled apps of current version
link	 : $(addprefix $(BUILD)/, $(APPS))

subdirs  : $(addsuffix .subdir, $(SUBS)) ; 

debug_subdirs : $(addsuffix .debug_subdir, $(SUBS)) ;

clean_subdirs : $(addsuffix .clean_subdir, $(SUBS)) ; 

%.subdir :
	$(MAKE) -C $*

%.debug_subdir :
	$(MAKE) -C $* debug

%.clean_subdir :
	$(MAKE) -C $* clean

$(addsuffix _OBJS, $(APPS)): %_OBJS : $(addprefix $(OBJDIR)/, $(%_SRCS:.c=.o)) ; 

build	: all

debug: DEBUG_FLAGS += -D_DEBUGGING_
debug: debug_subdirs $(APPS) $(SHLIBS)

# these targets just make the obj and build directories
$(BUILD): ; $(MKDIR) -p $(BUILD)
$(OBJDIR): ; $(MKDIR) -p $(OBJDIR)
$(SHLIBDIR): ; $(MKDIR) -p $(SHLIBDIR)

# depend on the app's main object file and its binary
$(APPS): %: $(OBJDIR)/%.o $(BUILD)/%.$(CV_BUILD_VERSION) ;

$(SHLIBDIR)/%.so  : %.c | $(SHLIBDIR)
	$(CC) $(CFLAGS) -shared -fPIC $^ -o $@

# source files depend at *least* on the conf.h and their own header
$(SRCS): %.c: $(HEADDIR)/conf.h $(HEADDIR)/%.h
	touch $@

# make object files under objdir from .c files
$(OBJDIR)/%.o : %.c | $(OBJDIR)
	$(CC) $(CFLAGS) -c $^ -o $@

# this target matches all $(APPS) under the $(BUILD) directory with .$(CV_BUILD_VERSION) appended to it
# it depends on the main object, the general objects and the build directory
$(addsuffix .$(CV_BUILD_VERSION), $(addprefix $(BUILD)/, $(APPS))): $(BUILD)/%.$(CV_BUILD_VERSION): $(OBJS) $(addprefix $(OBJDIR)/, $(%_SRCS:.c=.o)) $(OBJDIR)/%.o | $(BUILD) $(BUILD_REQ)
	$(CC) $(CFLAGS) $(DEPEND) $^ -o $@

# this target is for making the symlink to this version of APPS
$(addprefix $(BUILD)/, $(APPS)): $(BUILD)/%: $(BUILD)/%.$(CV_BUILD_VERSION)
	[ -e $@ ] && rm -f $@; ln -sf $*.$(CV_BUILD_VERSION) $@ || true

install: $(PROD) 
	/usr/bin/svc -d /etc/service/cellnet
	sleep 1
	cp $(BUILD)/cellnet $(BASEDIR)/bin
	/usr/bin/svc -u /etc/service/cellnet
	
unlink: ; $(RM) $(addprefix $(BUILD)/, $(APPS))

clean: unlink clean_subdirs
	$(RM) $(OBJS) 
	$(RM) $(SHLIBS)
	$(RM) $(addprefix $(OBJDIR)/, $(addsuffix .o, $(APPS)))
	$(RM) $(addprefix $(BUILD)/, $(addsuffix .$(CV_BUILD_VERSION), $(APPS)))

